 const quotes = [
  "Believe you can and you're halfway there.",
  "Do one thing every day that scares you.",
  "Dream big and dare to fail.",
  "Turn your wounds into wisdom.",
  "Don’t wait. The time will never be just right.",
  "Act as if what you do makes a difference. It does.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Never bend your head. Always hold it high. Look the world straight in the eye.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "In the middle of every difficulty lies opportunity.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "Start where you are. Use what you have. Do what you can.",
  "Limit your 'always' and your 'nevers'.",
  "Nothing is impossible. The word itself says 'I'm possible!'",
  "The only way to do great work is to love what you do.",
  "Don’t count the days, make the days count.",
  "You miss 100% of the shots you don’t take.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Opportunities don't happen, you create them.",
  "Do what you can, with what you have, where you are.",
  "Don’t let yesterday take up too much of today.",
  "If you can dream it, you can do it.",
  "Don’t watch the clock; do what it does. Keep going.",
  "Go the extra mile. It’s never crowded there.",
  "The future depends on what you do today.",
  "You are never too old to set another goal or to dream a new dream.",
  "Success doesn’t just find you. You have to go out and get it.",
  "Difficulties in life don’t come to destroy you, but to help you realize your hidden potential.",
  "Great things never come from comfort zones.",
  "Small progress is still progress.",
  "Push yourself, because no one else is going to do it for you.",
  "Don’t be afraid to give up the good to go for the great.",
  "Discipline is the bridge between goals and accomplishment.",
  "If you’re going through hell, keep going.",
  "Work hard in silence, let your success be the noise.",
  "Big journeys begin with small steps.",
  "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "If you get tired, learn to rest, not to quit.",
  "Courage is one step ahead of fear.",
  "Focus on being productive instead of busy.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "Don’t wish it were easier. Wish you were better.",
  "Opportunities multiply as they are seized.",
  "Your limitation—it’s only your imagination.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Dream it. Wish it. Do it.",
]

const size = quotes.length - 1